version: "3"
services:
  test:
    build: .
    image: marionebl/move_rs_dev
    volumes:
      - ".env:/home/rust/src/.env"
      - "./src:/home/rust/src/src"
      - "./tests:/home/rust/src/tests"
    command: cargo watch -x test
  serve:
    build: .
    image: marionebl/move_rs_dev
    ports:
      - "8000:8000"
    volumes:
      - ".env:/home/rust/src/.env"
      - "./src:/home/rust/src/src"
      - "./tests:/home/rust/src/tests"
    command: cargo watch -x run