version: "3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - '8001:8000'
    environment:
      AWS_DEFAULT_REGION: 'local'
      AWS_ACCESS_KEY_ID: 'test'
      AWS_SECRET_ACCESS_KEY: 'test'

  move-rs:
    build: .
    image: marionebl/move_rs_dev
    depends_on:
      - dynamodb
    ports:
      - "8000:8000"
      - "8443:8443"
    environment:
      AWS_DEFAULT_REGION: 'local'
      AWS_ACCESS_KEY_ID: 'test'
      AWS_SECRET_ACCESS_KEY: 'test'
    volumes:
      - "./.git:/home/rust/src/.git"
      - "./.circleci:/home/rust/src/.circleci"
      - "./extensions:/home/rust/src/extensions"
      - "./static:/home/rust/src/static"
      - "./src:/home/rust/src/src"
      - "./tests:/home/rust/src/tests"
      - "./.gitignore:/home/rust/src/.gitignore"
      - "./Dockerfile:/home/rust/src/.Dockerfile"
      - "./README.md:/home/rust/src/README.md"
      - "./rls-build.sh:/home/rust/src/rls-build.sh"
    command: code-server --allow-http --no-auth
