version: 2
jobs:
  build:
    docker:
      - image: brainpower/move-rs-cubicle
        user: root
    working_directory: /root/project
    steps:
      - checkout:
          path: /root/checkout
      - run:
          name: Mount sources
          command: cp -r /root/checkout/src /root/checkout/static /root/checkout/tests . 
      - run:
          name: Test
          command: cargo test