version: 2
jobs:
  build:
    docker:
      - image: marionebl/move_rs_dev
    working_directory: /root/project
    steps:
      - checkout:
          path: /root/repo
      - run:
          name: Mount sources
          command: cp -r /root/repo/src /root/repo/static /root/repo/tests . 
      - run:
          name: Test
          command: cargo test