version: 2
jobs:
  build:
    docker:
      - image: marionebl/move_rs_dev
    working_directory: /home/rust/src
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test